<?php

namespace Garnet\TaxiBeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EndroitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EndroitRepository extends EntityRepository
{
    public function listByName($name = null){
        $query = $this->createQueryBuilder('e')
            ->where('e.libelle like \'' . $name . '%\'')
            ->setMaxResults('10')
            ->getQuery()
            ->getResult();

        return $query;
    }
}
