<?php

namespace Garnet\TaxiBeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrajetBusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrajetBusRepository extends EntityRepository
{
}
