<?php

namespace Garnet\CooperativeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VilleRepository extends EntityRepository
{

    public function listByName($name = null){
        $query = $this->createQueryBuilder('v')
            ->where('v.nomVille like \'%' . $name . '%\'')
            ->setMaxResults('5')
            ->getQuery()
            ->getResult();

        return $query;
    }
}
